# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

brLoop <- function(x) {
    .Call('frpca_brLoop', PACKAGE = 'frpca', x)
}

getNorm <- function(x) {
    .Call('frpca_getNorm', PACKAGE = 'frpca', x)
}

mat_of_faces <- function(x, nrow, ncol) {
    .Call('frpca_mat_of_faces', PACKAGE = 'frpca', x, nrow, ncol)
}

mat_to_image <- function(x, dim) {
    .Call('frpca_mat_to_image', PACKAGE = 'frpca', x, dim)
}

rbrLoop <- function(x) {
    .Call('frpca_rbrLoop', PACKAGE = 'frpca', x)
}

